### ISSUE TITLE
Fizz Buzz Kata - NSScreencast

### ISSUE THREAD

**Issue by subdigital** [nsscreencast/comments#128]
Written on 11/18/2016 18:21:31 

URL: https://nsscreencast.com/episodes/245-fizz-buzz-kata

**Comment by subdigital** [comment]
originally written by **Alex Hedley** on **11/19/2016 14:42:09**

<p>I've not used atom before, have you installed the following packages?</p><p>language-swift (<a href="https://github.com/freebroccolo/atom-language-swift)" rel="nofollow noopener" title="https://github.com/freebroccolo/atom-language-swift)">https://github.com/freebroc...</a><br>file-icons (<a href="https://github.com/DanBrooker/file-icons)" rel="nofollow noopener" title="https://github.com/DanBrooker/file-icons)">https://github.com/DanBrook...</a></p>

**Comment by subdigital** [comment]
originally written by **subdigital** on **11/19/2016 15:50:35**

<p>set-icons, language-swift along with vim-mode and ex-mode as well.</p><p>There’s a autocomplete-swift, but I haven’t tried it yet.</p>

**Comment by subdigital** [comment]
originally written by **Tim Trautmann** on **12/23/2016 23:43:24**

<p>This doesn't seem to work with the MacOS Sierra stock version of ruby. When I try to bundle install, I get an error that ruby_dep-1.5.0 required ruby version &gt;= 2.2.5 and that it is not compatible with ruby 2.0.0p648.</p>

**Comment by subdigital** [comment]
originally written by **subdigital** on **12/24/2016 00:40:34**

<p>Looks like the 2.0.0 ruby is considered “insecure” by ruby_dep, so it fails to load. I’d recommend upgrading ruby.  A good guide for using rbenv to do this can be found here: <br><a href="https://gorails.com/setup/osx/10.12-sierra" rel="nofollow noopener" title="https://gorails.com/setup/osx/10.12-sierra">https://gorails.com/setup/o...</a></p>

**Comment by subdigital** [comment]
originally written by **Alex Hedley** on **01/08/2017 16:12:30**

<p>Thought these steps might be helpful to others who might also have issues:</p><p>I followed the below link, updated ruby but still get:<br></p><pre><code><br>ruby_dep-1.5.0 requires ruby version &gt;= 2.2.5, which is incompatible with the current version, ruby 2.0.0p648<br>Alexanders-MBP:Katas AlexHedley$ ruby -v<br>ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]<br></code></pre><p></p><p>Rebooted then tried 'bundle install' and got the following error<br></p><pre><code><br>/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:296:in `to_specs': Could not find 'bundler' (&gt;= 0) among 19 total gem(s) (Gem::LoadError)<br>from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency.rb:307:in `to_spec'<br>from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_gem.rb:47:in `gem'<br>from /usr/local/bin/bundle:22:in `&lt;main&gt;'<br></code></pre><p></p><p>So I installed the bundler gem</p><p></p><pre><code><br>gem install bundler<br></code></pre><p></p><p>Then ran the<br></p><pre><code><br> bundle install<br></code></pre>

**Comment by subdigital** [comment]
originally written by **subdigital** on **01/08/2017 17:12:24**

<p>I think you're close!  Try running rbenv global 2.3 or whatever ruby you installed. This will make the default the one from rbenv instead of system ruby.</p>

**Comment by subdigital** [comment]
originally written by **Alex Hedley** on **01/08/2017 17:20:28**

<p>Got it working now, thanks</p>

**Comment by subdigital** [comment]
originally written by **niky** on **05/07/2017 19:49:08**

<p>Nice! `gem install bundler ` saved my day :) Thanks</p>
